import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationTop from "@/components/marketing/NavigationTop";
import { ThemeProvider } from "@/components/providers/ShadcnProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            <NavigationTop />
          </div>
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
